# Generated by Django 5.2 on 2025-04-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductPrice',
        ),
    ]
