# Generated by Django 5.2 on 2025-05-01 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_color_fabric_size_remove_productattribute_attribute_and_more'),
    ]

    operations = [
    ]
