# Generated by Django 5.2 on 2025-04-24 10:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewaySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(choices=[('STRIPE', 'Stripe'), ('RAZORPAY', 'Razorpay'), ('PAYPAL', 'PayPal'), ('PAYU', 'PayU'), ('PAYUMONEY', 'PayUmoney'), ('INSTAMOJO', 'Instamojo'), ('CASHFREE', 'Cashfree'), ('PAYTM', 'Paytm')], max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('display_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('api_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('merchant_id', models.CharField(blank=True, max_length=255, null=True)),
                ('webhook_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('test_mode', models.BooleanField(default=True)),
                ('additional_settings', models.JSONField(blank=True, null=True)),
                ('payment_methods', models.JSONField(blank=True, help_text='List of supported payment methods as JSON', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Gateway Setting',
                'verbose_name_plural': 'Payment Gateway Settings',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('UPI', 'UPI'), ('NET_BANKING', 'Net Banking'), ('WALLET', 'Wallet'), ('COD', 'Cash on Delivery'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('card_last_four', models.CharField(blank=True, max_length=4, null=True)),
                ('card_brand', models.CharField(blank=True, max_length=20, null=True)),
                ('card_exp_month', models.CharField(blank=True, max_length=2, null=True)),
                ('card_exp_year', models.CharField(blank=True, max_length=4, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=50, null=True)),
                ('wallet_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('tokenized_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='INITIATED', max_length=20)),
                ('gateway_refund_id', models.CharField(blank=True, max_length=255, null=True)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(choices=[('STRIPE', 'Stripe'), ('RAZORPAY', 'Razorpay'), ('PAYPAL', 'PayPal'), ('PAYU', 'PayU'), ('PAYUMONEY', 'PayUmoney'), ('INSTAMOJO', 'Instamojo'), ('CASHFREE', 'Cashfree'), ('PAYTM', 'Paytm')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded'), ('CANCELLED', 'Cancelled')], default='INITIATED', max_length=20)),
                ('payment_method', models.CharField(max_length=50)),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('gateway_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_test', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(choices=[('STRIPE', 'Stripe'), ('RAZORPAY', 'Razorpay'), ('PAYPAL', 'PayPal'), ('PAYU', 'PayU'), ('PAYUMONEY', 'PayUmoney'), ('INSTAMOJO', 'Instamojo'), ('CASHFREE', 'Cashfree'), ('PAYTM', 'Paytm')], max_length=20)),
                ('event_type', models.CharField(choices=[('PAYMENT_INTENT_SUCCEEDED', 'Payment Intent Succeeded'), ('PAYMENT_INTENT_FAILED', 'Payment Intent Failed'), ('CHARGE_SUCCEEDED', 'Charge Succeeded'), ('CHARGE_FAILED', 'Charge Failed'), ('CHARGE_REFUNDED', 'Charge Refunded'), ('CHECKOUT_COMPLETED', 'Checkout Completed'), ('CHECKOUT_FAILED', 'Checkout Failed'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('event_id', models.CharField(max_length=255)),
                ('is_test', models.BooleanField(default=True)),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
