# Generated by Django 5.2 on 2025-05-01 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_cart_discount_amount_cart_shipping_cost_and_more'),
        ('products', '0004_color_fabric_size_remove_productattribute_attribute_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='guestcartitem',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.color'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='fabric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.fabric'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.size'),
        ),
        migrations.AddField(
            model_name='guestcartitem',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.color'),
        ),
        migrations.AddField(
            model_name='guestcartitem',
            name='fabric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.fabric'),
        ),
        migrations.AddField(
            model_name='guestcartitem',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.size'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.color'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.fabric'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.size'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'size', 'color', 'fabric')},
        ),
        migrations.AlterUniqueTogether(
            name='guestcartitem',
            unique_together={('cart', 'product', 'size', 'color', 'fabric')},
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('wishlist', 'product', 'size', 'color', 'fabric')},
        ),
    ]
